export * from "./EmployeeOverview/departments/createDepartment"
export * from "./EmployeeOverview/departments/getDepartments"
export * from "./EmployeeOverview/departments/deleteDepartment"
export * from "./EmployeeOverview/departments/updateDepartment"

export * from "./EmployeeOverview/departmentProportion/createDepartmentProportion"
export * from "./EmployeeOverview/departmentProportion/deleteDepartmentProportion"
export * from "./EmployeeOverview/departmentProportion/getDepartmentProportions"
export * from "./EmployeeOverview/departmentProportion/updateDepartment"
export * from "./EmployeeOverview/departmentProportion/latest"

export * from "./EmployeeOverview/positions/createPosition"
export * from "./EmployeeOverview/positions/getPositions"
export * from "./EmployeeOverview/positions/deletePosition"
export * from "./EmployeeOverview/positions/updatePosition"

export * from "./EmployeeOverview/positionProportion/createPositionProportion"
export * from "./EmployeeOverview/positionProportion/deletePositionProportion"
export * from "./EmployeeOverview/positionProportion/getPositionProportions"
export * from "./EmployeeOverview/positionProportion/updatePosition"
export * from "./EmployeeOverview/positionProportion/latest"

export * from "./EmployeeOverview/contractDistribution/createContractDist"
export * from "./EmployeeOverview/contractDistribution/getContractDists"
export * from "./EmployeeOverview/contractDistribution/deleteContractDist"
export * from "./EmployeeOverview/contractDistribution/updateContractDist"
export * from "./EmployeeOverview/contractDistribution/latest"

export * from "./EmployeeOverview/shiftDistribution/createShiftDist"
export * from "./EmployeeOverview/shiftDistribution/getShiftDists"
export * from "./EmployeeOverview/shiftDistribution/deleteShiftDist"
export * from "./EmployeeOverview/shiftDistribution/updateShiftDist"
export * from "./EmployeeOverview/shiftDistribution/latest"

export * from "./EmployeeOverview/ages/createAge"
export * from "./EmployeeOverview/ages/getAges"
export * from "./EmployeeOverview/ages/deleteAge"
export * from "./EmployeeOverview/ages/updateAge"

export * from "./EmployeeOverview/averageAges/createAverageAge"
export * from "./EmployeeOverview/averageAges/deleteAverageAge"
export * from "./EmployeeOverview/averageAges/getAverageAges"
export * from "./EmployeeOverview/averageAges/updateAverageAge"
export * from "./EmployeeOverview/averageAges/latest"

export * from "./EmployeeOverview/gender/createGender"
export * from "./EmployeeOverview/gender/getGenders"
export * from "./EmployeeOverview/gender/deleteGender"
export * from "./EmployeeOverview/gender/updateGender"
export * from "./EmployeeOverview/gender/latest"

export * from "./EmployeeOverview/employeeStats/createEmployeeStats"
export * from "./EmployeeOverview/employeeStats/getEmployeeStats"
export * from "./EmployeeOverview/employeeStats/updateEmployeeStats"
export * from "./EmployeeOverview/employeeStats/deleteEmployeeStats"
export * from "./EmployeeOverview/employeeStats/latest"

export * from "./EmployeeExperience/yearsWithUniversity/create"
export * from "./EmployeeExperience/yearsWithUniversity/get"
export * from "./EmployeeExperience/yearsWithUniversity/update"
export * from "./EmployeeExperience/yearsWithUniversity/delete"
export * from "./EmployeeExperience/yearsWithUniversity/latest"

export * from "./EmployeeExperience/averageExperienceDepartment/create"
export * from "./EmployeeExperience/averageExperienceDepartment/get"
export * from "./EmployeeExperience/averageExperienceDepartment/update"
export * from "./EmployeeExperience/averageExperienceDepartment/delete"
export * from "./EmployeeExperience/averageExperienceDepartment/latest"

export * from "./EmployeeExperience/averageExperienceCategory/create"
export * from "./EmployeeExperience/averageExperienceCategory/get"
export * from "./EmployeeExperience/averageExperienceCategory/update"
export * from "./EmployeeExperience/averageExperienceCategory/delete"
export * from "./EmployeeExperience/averageExperienceCategory/latest"

export * from "./EmployeeDemographics/StaffCategoryGender/create"
export * from "./EmployeeDemographics/StaffCategoryGender/get"
export * from "./EmployeeDemographics/StaffCategoryGender/update"
export * from "./EmployeeDemographics/StaffCategoryGender/delete"
export * from "./EmployeeDemographics/StaffCategoryGender/latest"

export * from "./EmployeeDemographics/StaffNationality/create"
export * from "./EmployeeDemographics/StaffNationality/get"
export * from "./EmployeeDemographics/StaffNationality/update"
export * from "./EmployeeDemographics/StaffNationality/delete"
export * from "./EmployeeDemographics/StaffNationality/latest"

export * from "./EmployeeDemographics/StaffPosition/create"
export * from "./EmployeeDemographics/StaffPosition/get"
export * from "./EmployeeDemographics/StaffPosition/update"
export * from "./EmployeeDemographics/StaffPosition/delete"
export * from "./EmployeeDemographics/StaffPosition/latest"

export * from "./EmployeeDemographics/AgeGroups/create"
export * from "./EmployeeDemographics/AgeGroups/get"
export * from "./EmployeeDemographics/AgeGroups/update"
export * from "./EmployeeDemographics/AgeGroups/delete"
export * from "./EmployeeDemographics/AgeGroups/latest"

export * from "./EmployeeDemographics/StaffByCategory/create"
export * from "./EmployeeDemographics/StaffByCategory/get"
export * from "./EmployeeDemographics/StaffByCategory/update"
export * from "./EmployeeDemographics/StaffByCategory/delete"
export * from "./EmployeeDemographics/StaffByCategory/latest"

export * from "./Turnover/terminationYears/create"
export * from "./Turnover/terminationYears/get"
export * from "./Turnover/terminationYears/update"
export * from "./Turnover/terminationYears/delete"
export * from "./Turnover/terminationYears/latest"

export * from "./Turnover/terminationMonths/create"
export * from "./Turnover/terminationMonths/get"
export * from "./Turnover/terminationMonths/update"
export * from "./Turnover/terminationMonths/delete"
export * from "./Turnover/terminationMonths/latest"

export * from "./Turnover/terminationReason/create"
export * from "./Turnover/terminationReason/get"
export * from "./Turnover/terminationReason/update"
export * from "./Turnover/terminationReason/delete"
export * from "./Turnover/terminationReason/latest"

export * from "./Turnover/terminationRateCategory/create"
export * from "./Turnover/terminationRateCategory/get"
export * from "./Turnover/terminationRateCategory/update"
export * from "./Turnover/terminationRateCategory/delete"
export * from "./Turnover/terminationRateCategory/latest"

export * from "./DMS/ActiveUsers/create"
export * from "./DMS/ActiveUsers/get"
export * from "./DMS/ActiveUsers/update"
export * from "./DMS/ActiveUsers/delete"
export * from "./DMS/ActiveUsers/latest"

export * from "./DMS/AverageTimeApprove/create"
export * from "./DMS/AverageTimeApprove/get"
export * from "./DMS/AverageTimeApprove/update"
export * from "./DMS/AverageTimeApprove/delete"
export * from "./DMS/AverageTimeApprove/latest"

export * from "./DMS/DocsByType/create"
export * from "./DMS/DocsByType/get"
export * from "./DMS/DocsByType/update"
export * from "./DMS/DocsByType/delete"
export * from "./DMS/DocsByType/latest"

export * from "./DMS/DocsPendingApproval/create"
export * from "./DMS/DocsPendingApproval/get"
export * from "./DMS/DocsPendingApproval/update"
export * from "./DMS/DocsPendingApproval/delete"
export * from "./DMS/DocsPendingApproval/latest"

export * from "./DMS/DocsStatusDist/create"
export * from "./DMS/DocsStatusDist/get"
export * from "./DMS/DocsStatusDist/update"
export * from "./DMS/DocsStatusDist/delete"
export * from "./DMS/DocsStatusDist/latest"

export * from "./DMS/TopTenSignedPersonel/create"
export * from "./DMS/TopTenSignedPersonel/get"
export * from "./DMS/TopTenSignedPersonel/update"
export * from "./DMS/TopTenSignedPersonel/delete"
export * from "./DMS/TopTenSignedPersonel/latest"

export * from "./DMS/TotalDocsPerMonth/create"
export * from "./DMS/TotalDocsPerMonth/get"
export * from "./DMS/TotalDocsPerMonth/update"
export * from "./DMS/TotalDocsPerMonth/delete"
export * from "./DMS/TotalDocsPerMonth/latest"

export * from "./DMS/TotalDocsPerYear/create"
export * from "./DMS/TotalDocsPerYear/get"
export * from "./DMS/TotalDocsPerYear/update"
export * from "./DMS/TotalDocsPerYear/delete"
export * from "./DMS/TotalDocsPerYear/latest"

export * from "./Recruitment/openPositions/create"
export * from "./Recruitment/openPositions/get"
export * from "./Recruitment/openPositions/update"
export * from "./Recruitment/openPositions/delete"
export * from "./Recruitment/openPositions/latest"

export * from "./Recruitment/offers/create"
export * from "./Recruitment/offers/get"
export * from "./Recruitment/offers/update"
export * from "./Recruitment/offers/delete"
export * from "./Recruitment/offers/latest"

export * from "./Recruitment/timeHireByCategory/create"
export * from "./Recruitment/timeHireByCategory/get"
export * from "./Recruitment/timeHireByCategory/update"
export * from "./Recruitment/timeHireByCategory/delete"
export * from "./Recruitment/timeHireByCategory/latest"

export * from "./Recruitment/interviewsByCategory/create"
export * from "./Recruitment/interviewsByCategory/get"
export * from "./Recruitment/interviewsByCategory/update"
export * from "./Recruitment/interviewsByCategory/delete"
export * from "./Recruitment/interviewsByCategory/latest"

export * from "./Recruitment/hiredCandidates/create"
export * from "./Recruitment/hiredCandidates/get"
export * from "./Recruitment/hiredCandidates/update"
export * from "./Recruitment/hiredCandidates/delete"
export * from "./Recruitment/hiredCandidates/latest"

export * from "./Recruitment/offersAcceptance/create"
export * from "./Recruitment/offersAcceptance/get"
export * from "./Recruitment/offersAcceptance/update"
export * from "./Recruitment/offersAcceptance/delete"
export * from "./Recruitment/offersAcceptance/latest"

export * from "./Recruitment/positionFilledByCategory/create"
export * from "./Recruitment/positionFilledByCategory/get"
export * from "./Recruitment/positionFilledByCategory/update"
export * from "./Recruitment/positionFilledByCategory/delete"
export * from "./Recruitment/positionFilledByCategory/latest"

export * from "./Recruitment/readvertisedPositions/create"
export * from "./Recruitment/readvertisedPositions/get"
export * from "./Recruitment/readvertisedPositions/update"
export * from "./Recruitment/readvertisedPositions/delete"
export * from "./Recruitment/readvertisedPositions/latest"

export * from "./AskWIUT/AverageTimeCall/create"
export * from "./AskWIUT/AverageTimeCall/get"
export * from "./AskWIUT/AverageTimeCall/update"
export * from "./AskWIUT/AverageTimeCall/delete"
export * from "./AskWIUT/AverageTimeCall/latest"

export * from "./AskWIUT/BotInquiries/create"
export * from "./AskWIUT/BotInquiries/get"
export * from "./AskWIUT/BotInquiries/update"
export * from "./AskWIUT/BotInquiries/delete"
export * from "./AskWIUT/BotInquiries/latest"

export * from "./AskWIUT/CallCenterInquiriesByCategory/create"
export * from "./AskWIUT/CallCenterInquiriesByCategory/get"
export * from "./AskWIUT/CallCenterInquiriesByCategory/update"
export * from "./AskWIUT/CallCenterInquiriesByCategory/delete"
export * from "./AskWIUT/CallCenterInquiriesByCategory/latest"

export * from "./AskWIUT/FrequentInquiriesByCategory/create"
export * from "./AskWIUT/FrequentInquiriesByCategory/get"
export * from "./AskWIUT/FrequentInquiriesByCategory/update"
export * from "./AskWIUT/FrequentInquiriesByCategory/delete"
export * from "./AskWIUT/FrequentInquiriesByCategory/latest"

export * from "./AskWIUT/FrequentInquiriesCenter/create"
export * from "./AskWIUT/FrequentInquiriesCenter/get"
export * from "./AskWIUT/FrequentInquiriesCenter/update"
export * from "./AskWIUT/FrequentInquiriesCenter/delete"
export * from "./AskWIUT/FrequentInquiriesCenter/latest"

export * from "./AskWIUT/HourlyCallsCenter/create"
export * from "./AskWIUT/HourlyCallsCenter/get"
export * from "./AskWIUT/HourlyCallsCenter/update"
export * from "./AskWIUT/HourlyCallsCenter/delete"
export * from "./AskWIUT/HourlyCallsCenter/latest"

export * from "./AskWIUT/NumberOfInquiriesByType/create"
export * from "./AskWIUT/NumberOfInquiriesByType/get"
export * from "./AskWIUT/NumberOfInquiriesByType/update"
export * from "./AskWIUT/NumberOfInquiriesByType/delete"
export * from "./AskWIUT/NumberOfInquiriesByType/latest"

export * from "./AskWIUT/NumberOfInquiriesByTypeCategory/create"
export * from "./AskWIUT/NumberOfInquiriesByTypeCategory/get"
export * from "./AskWIUT/NumberOfInquiriesByTypeCategory/update"
export * from "./AskWIUT/NumberOfInquiriesByTypeCategory/delete"

export * from "./AskWIUT/WeeklyCallsCenter/create"
export * from "./AskWIUT/WeeklyCallsCenter/get"
export * from "./AskWIUT/WeeklyCallsCenter/update"
export * from "./AskWIUT/WeeklyCallsCenter/delete"
export * from "./AskWIUT/WeeklyCallsCenter/latest"

export * from "./AskWIUT/WeeklyCustomersCenter/create"
export * from "./AskWIUT/WeeklyCustomersCenter/get"
export * from "./AskWIUT/WeeklyCustomersCenter/update"
export * from "./AskWIUT/WeeklyCustomersCenter/delete"
export * from "./AskWIUT/WeeklyCustomersCenter/latest"

export * from "./AskWIUT/YearlyCallsCenter/create"
export * from "./AskWIUT/YearlyCallsCenter/get"
export * from "./AskWIUT/YearlyCallsCenter/update"
export * from "./AskWIUT/YearlyCallsCenter/delete"
export * from "./AskWIUT/YearlyCallsCenter/latest"

export * from "./AskWIUT/YearlyTotalMinCalls/create"
export * from "./AskWIUT/YearlyTotalMinCalls/get"
export * from "./AskWIUT/YearlyTotalMinCalls/update"
export * from "./AskWIUT/YearlyTotalMinCalls/delete"
export * from "./AskWIUT/YearlyTotalMinCalls/latest"

export * from "./AskWIUT/BotInquiriesTrend/create"
export * from "./AskWIUT/BotInquiriesTrend/get"
export * from "./AskWIUT/BotInquiriesTrend/update"
export * from "./AskWIUT/BotInquiriesTrend/delete"
export * from "./AskWIUT/BotInquiriesTrend/latest"

export * from "./AskWIUT/CallCenterInquiriesByCategoryTrend/create"
export * from "./AskWIUT/CallCenterInquiriesByCategoryTrend/get"
export * from "./AskWIUT/CallCenterInquiriesByCategoryTrend/update"
export * from "./AskWIUT/CallCenterInquiriesByCategoryTrend/delete"
export * from "./AskWIUT/CallCenterInquiriesByCategoryTrend/latest"

export * from "./AskWIUT/FrequentInquiriesByCategoryTrend/create"
export * from "./AskWIUT/FrequentInquiriesByCategoryTrend/get"
export * from "./AskWIUT/FrequentInquiriesByCategoryTrend/update"
export * from "./AskWIUT/FrequentInquiriesByCategoryTrend/delete"
export * from "./AskWIUT/FrequentInquiriesByCategoryTrend/latest"

export * from "./AskWIUT/FrequentInquiriesCenterTrend/create"
export * from "./AskWIUT/FrequentInquiriesCenterTrend/get"
export * from "./AskWIUT/FrequentInquiriesCenterTrend/update"
export * from "./AskWIUT/FrequentInquiriesCenterTrend/delete"
export * from "./AskWIUT/FrequentInquiriesCenterTrend/latest"

export * from "./AskWIUT/HourlyCallsCenterTrend/create"
export * from "./AskWIUT/HourlyCallsCenterTrend/get"
export * from "./AskWIUT/HourlyCallsCenterTrend/update"
export * from "./AskWIUT/HourlyCallsCenterTrend/delete"
export * from "./AskWIUT/HourlyCallsCenterTrend/latest"

export * from "./AskWIUT/NumberOfInquiriesByTypeTrend/create"
export * from "./AskWIUT/NumberOfInquiriesByTypeTrend/get"
export * from "./AskWIUT/NumberOfInquiriesByTypeTrend/update"
export * from "./AskWIUT/NumberOfInquiriesByTypeTrend/delete"
export * from "./AskWIUT/NumberOfInquiriesByTypeTrend/latest"

export * from "./AskWIUT/WeeklyCallsCenterTrend/create"
export * from "./AskWIUT/WeeklyCallsCenterTrend/get"
export * from "./AskWIUT/WeeklyCallsCenterTrend/update"
export * from "./AskWIUT/WeeklyCallsCenterTrend/delete"
export * from "./AskWIUT/WeeklyCallsCenterTrend/latest"

export * from "./AskWIUT/WeeklyCustomersCenterTrend/create"
export * from "./AskWIUT/WeeklyCustomersCenterTrend/get"
export * from "./AskWIUT/WeeklyCustomersCenterTrend/update"
export * from "./AskWIUT/WeeklyCustomersCenterTrend/delete"
export * from "./AskWIUT/WeeklyCustomersCenterTrend/latest"

export * from "./AskWIUT/TrendYearsNames/create"
export * from "./AskWIUT/TrendYearsNames/get"
export * from "./AskWIUT/TrendYearsNames/update"
export * from "./AskWIUT/TrendYearsNames/delete"
export * from "./AskWIUT/TrendYearsNames/latest"
